# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  # For Conventional Commits.
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v4.0.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
        args: [build, chore, ci, docs, feat, fix, perf, refactor, revert, style, test]
  # Default hooks.
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-vcs-permalinks
      - id: check-xml
      - id: check-yaml
        exclude: pnpm-lock.yaml
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: trailing-whitespace
  # Use JSON5 instead of JSON.
  - repo: https://gitlab.com/bmares/check-json5
    rev: v1.0.0
    hooks:
      - id: check-json5
  # Detect some secrets in code...
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
      - id: detect-secrets
        args: ["--baseline", ".secrets.baseline"]
        exclude: ""
  - repo: local
    hooks:
      - id: pnpm
        name: Format files
        language: system
        entry: pnpm format
